;/*FB_PKG_DELIM*/

__d("EventListenerWWW",["cr:1353359"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:1353359")}),98);
__d("FBJSON",[],(function(a,b,c,d,e,f){a=JSON.parse;b=JSON.stringify;f.parse=a;f.stringify=b}),66);
__d("HeroInteractionContext",["react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b=function(){};c={consumeBootload:b,hold:function(){return""},logHeroRender:b,logMetadata:b,logPageletVC:b,logReactCommit:b,logReactPostCommit:b,logReactRender:b,pageletStack:[],registerPlaceholder:b,removePlaceholder:b,suspenseCallback:b,unhold:b};e=a.createContext(c);g.DEFAULT_CONTEXT_VALUE=c;g.Context=e}),98);
__d("HeroInteractionIDContext",["react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b=a.createContext(null);g["default"]=b}),98);
__d("HeroComponent.react",["HeroInteractionContext","HeroInteractionIDContext","react","react-compiler-runtime"],(function(a,b,c,d,e,f,g){"use strict";var h;b=h||(h=d("react"));e=h;var i=e.useContext,j=e.useLayoutEffect;function a(a){var b=d("react-compiler-runtime").c(5),e=a.description,f=i(d("HeroInteractionContext").Context),g=i(c("HeroInteractionIDContext")),h;b[0]!==e||b[1]!==f||b[2]!==g?(a=function(){g!=null&&f.logHeroRender(g,e,f.pageletStack)},h=[e,f,g],b[0]=e,b[1]=f,b[2]=g,b[3]=a,b[4]=h):(a=b[3],h=b[4]);j(a,h);return null}a.displayName="HeroComponent";f=b.memo(a);g["default"]=f}),98);
__d("HeroCurrentInteractionForLoggingContext",["react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b=a.createContext({current:null});g["default"]=b}),98);
__d("HeroFallbackTracker.react",["HeroInteractionContext","HeroInteractionIDContext","react","react-compiler-runtime"],(function(a,b,c,d,e,f,g){"use strict";var h;b=h||d("react");var i=b.useContext,j=b.useLayoutEffect;function a(a){var b=d("react-compiler-runtime").c(5),e=a.uuid,f=i(d("HeroInteractionContext").Context),g=i(c("HeroInteractionIDContext")),h;b[0]!==f||b[1]!==g||b[2]!==e?(a=function(){if(g!=null){f.registerPlaceholder(g,e,f.pageletStack);return function(){f.removePlaceholder(g,e)}}},h=[f,g,e],b[0]=f,b[1]=g,b[2]=e,b[3]=a,b[4]=h):(a=b[3],h=b[4]);j(a,h);return null}a.displayName="HeroFallbackTracker";g["default"]=a}),98);
__d("HeroHoldTrigger.react",["HeroInteractionContext","HeroInteractionIDContext","react","react-compiler-runtime"],(function(a,b,c,d,e,f,g){"use strict";var h;b=h||d("react");var i=b.useContext,j=b.useLayoutEffect;function a(a){var b=d("react-compiler-runtime").c(6),e=a.description,f=a.hold,g=i(d("HeroInteractionContext").Context),h=i(c("HeroInteractionIDContext")),k;b[0]!==e||b[1]!==g||b[2]!==f||b[3]!==h?(a=function(){if(f&&h!=null){var a=g.hold(h,g.pageletStack,e);return function(){g.unhold(h,a)}}},k=[e,g,h,f],b[0]=e,b[1]=g,b[2]=f,b[3]=h,b[4]=a,b[5]=k):(a=b[4],k=b[5]);j(a,k);return null}a.displayName="HeroHoldTrigger";g["default"]=a}),98);
__d("react-relay/relay-hooks/ProfilerContext",["react"],(function(a,b,c,d,e,f){"use strict";var g;a=g||b("react");c=a.createContext({wrapPrepareQueryResource:function(a){return a()}});e.exports=c}),null);
__d("RelayProfilerContext",["react-relay/relay-hooks/ProfilerContext"],(function(a,b,c,d,e,f,g){g["default"]=c("react-relay/relay-hooks/ProfilerContext")}),98);
__d("HeroInteractionContextPassthrough.react",["HeroCurrentInteractionForLoggingContext","HeroInteractionContext","HeroInteractionIDContext","RelayProfilerContext","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||(h=d("react")),j=h.use,k={current:null},l={consumeBootload:function(){},retainQuery:function(){},wrapPrepareQueryResource:function(a){return a()}};function a(a){var b=a.children;a=a.clear;a=a===void 0?!0:a;return i.jsx(d("HeroInteractionContext").Context.Provider,{value:a?d("HeroInteractionContext").DEFAULT_CONTEXT_VALUE:j(d("HeroInteractionContext").Context),children:i.jsx(c("HeroCurrentInteractionForLoggingContext").Provider,{value:a?k:j(c("HeroCurrentInteractionForLoggingContext")),children:i.jsx(c("HeroInteractionIDContext").Provider,{value:a?null:j(c("HeroInteractionIDContext")),children:i.jsx(c("RelayProfilerContext").Provider,{value:a?l:j(c("RelayProfilerContext")),children:b})})})})}a.displayName=a.name+" [from "+f.id+"]";a.displayName="HeroInteractionContextPassthrough";g["default"]=a}),98);
__d("HeroPendingPlaceholderTracker",[],(function(a,b,c,d,e,f){"use strict";var g=new Map();function a(a){g.has(a)||g.set(a,new Map())}function b(a,b,c,d,e){a=g.get(a);a&&a.set(b,{description:c,startTime:d,pageletStack:e})}function c(a){a=g.get(a);return a?Array.from(a.values()):[]}function d(a){g["delete"](a)}function e(a,b){a=g.get(a);a&&a["delete"](b)}function h(a){return g.has(a)}f.addInteraction=a;f.addPlaceholder=b;f.dump=c;f.removeInteraction=d;f.removePlaceholder=e;f.isInteractionActive=h}),66);
__d("HeroPlaceholderUtils",["PromiseAnnotate"],(function(a,b,c,d,e,f,g){"use strict";var h,i=0;function a(){return String(i++)}function b(a){if(a!=null&&a.size>0)return Array.from(a).map(function(a){a=(h||(h=d("PromiseAnnotate"))).getDisplayName(a);if(a!=null)return a;else return"Promise"}).join(",");else return null}g.getSimpleUUID=a;g.createThenableDescription=b}),98);
__d("HeroPlaceholder.react",["HeroFallbackTracker.react","HeroInteractionContext","HeroInteractionIDContext","HeroPlaceholderUtils","react","react-compiler-runtime","useStable"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||(h=d("react"));b=h;b.useCallback;var j=b.useContext,k=b.useLayoutEffect,l=b.useRef;e=function(a){a=a.children;return a};function m(a){var b=d("react-compiler-runtime").c(2),c=a.cb,e=l(!1);b[0]!==c?(a=function(){e.current||(c(),e.current=!0)},b[0]=c,b[1]=a):a=b[1];k(a,[c]);return null}function a(a){var b=d("react-compiler-runtime").c(35),e=a.children,f=a.fallback,g=a.name,h=a.unstable_avoidThisFallback,n=a.unstable_onSuspense,o=j(d("HeroInteractionContext").Context),p=j(c("HeroInteractionIDContext")),q=c("useStable")(d("HeroPlaceholderUtils").getSimpleUUID),r=(a=a.placeholderUUID)!=null?a:q,s=c("useStable")(d("HeroPlaceholderUtils").getSimpleUUID),t=l(!1);a=e;b[3]!==o||b[4]!==p||b[5]!==g||b[6]!==r||b[7]!==n?(q=function(a){p!=null&&o.suspenseCallback(p,r,o.pageletStack,a,g!=null?g:"Unnamed Suspense");if(n){a=(a=d("HeroPlaceholderUtils").createThenableDescription(a))!=null?a:"";n(a)}},b[3]=o,b[4]=p,b[5]=g,b[6]=r,b[7]=n,b[8]=q):q=b[8];e=q;var u;b[9]!==o||b[10]!==p||b[11]!==g||b[12]!==s?(q=function(){if(t.current===!1&&p!=null&&p!=null){o.hold(p,o.pageletStack,"Hydration",s,g);return function(){return o.unhold(p,s)}}},u=[o,p,g,s],b[9]=o,b[10]=p,b[11]=g,b[12]=s,b[13]=q,b[14]=u):(q=b[13],u=b[14]);k(q,u);b[15]!==o||b[16]!==p||b[17]!==s?(q=function(){t.current=!0,p!=null&&o.unhold(p,s)},b[15]=o,b[16]=p,b[17]=s,b[18]=q):q=b[18];u=q;b[19]!==u?(q=i.jsx(m,{cb:u}),b[19]=u,b[20]=q):q=b[20];var v;b[21]!==r?(v=i.jsx(c("HeroFallbackTracker.react"),{uuid:r}),b[21]=r,b[22]=v):v=b[22];var w;b[23]!==f||b[24]!==q||b[25]!==v?(w=i.jsxs(i.Fragment,{children:[f,q,v]}),b[23]=f,b[24]=q,b[25]=v,b[26]=w):w=b[26];b[27]!==u?(f=i.jsx(m,{cb:u}),b[27]=u,b[28]=f):f=b[28];b[29]!==e||b[30]!==w||b[31]!==f||b[32]!==h||b[33]!==a?(q=i.jsxs(i.Suspense,{fallback:w,suspenseCallback:e,unstable_avoidThisFallback:h,children:[f,a]}),b[29]=e,b[30]=w,b[31]=f,b[32]=h,b[33]=a,b[34]=q):q=b[34];return q}a.displayName="HeroPlaceholder";g["default"]=a}),98);
__d("InlineFbtResult",["cr:1183579"],(function(a,b,c,d,e,f,g){g["default"]=b("cr:1183579")}),98);
__d("React.classic",["cr:1292365"],(function(a,b,c,d,e,f){e.exports=b("cr:1292365")}),null);
__d("ReactDOM.classic",["cr:13683","cr:5277"],(function(a,b,c,d,e,f){b("cr:13683")&&b("cr:13683")(),e.exports=b("cr:5277")}),null);
__d("ReactDOMCompatibilityLayer",["ReactDOM"],(function(a,b,c,d,e,f,g){"use strict";var h=typeof WeakMap==="function"?new WeakMap():new Map();function a(a,b){var c=h.get(b);c==null&&(c=d("ReactDOM").createRoot(b),h.set(b,c));b=null;var e=a.props.ref;d("ReactDOM").flushSync(function(){var d;return(d=c)==null?void 0:d.render(typeof a.type==="string"||(d=a.type)!=null&&(d=d.prototype)!=null&&d.isReactComponent?babelHelpers["extends"]({},a,{props:babelHelpers["extends"]({},a.props,{ref:function(a){typeof e==="function"?e(a):e!=null&&(e.current=a),b=a}})}):a)});return b}function b(a){if(a==null)return!1;var b=h.get(a);if(b){d("ReactDOM").flushSync(function(){b.unmount()});h["delete"](a);return!0}return!1}g.render_DEPRECATED=a;g.unmountComponentAtNode_DEPRECATED=b}),98);
__d("ReactFeatureFlags",["gkx","qex"],(function(a,b,c,d,e,f,g){"use strict";var h,i,j;a=c("gkx")("11557");b=c("gkx")("11685");d=!0;e=c("gkx")("10839");f=c("gkx")("21072")||((f=c("qex")._("104"))!=null?f:!1);h=(h=c("qex")._("128"))!=null?h:250;i=(i=c("qex")._("344"))!=null?i:5e3;j=(j=c("qex")._("388"))!=null?j:5e3;var k=!1,l=!1,m=c("gkx")("21063"),n=!0,o=c("gkx")("2815"),p=c("gkx")("10850"),q=!1,r=!1,s=!1;c=!p&&c("gkx")("21069")||c("gkx")("10211");g.alwaysThrottleRetries=a;g.enableNoCloningMemoCache=b;g.enableObjectFiber=d;g.enableHiddenSubtreeInsertionEffectCleanup=e;g.enableRetryLaneExpiration=f;g.syncLaneExpirationMs=h;g.transitionLaneExpirationMs=i;g.retryLaneExpirationMs=j;g.enableScrollEndPolyfill=k;g.enableInfiniteRenderLoopDetection=l;g.enableTrustedTypesIntegration=m;g.enableFragmentRefs=n;g.enableViewTransition=o;g.enableComponentPerformanceTrack=p;g.enableTransitionTracing=q;g.renameElementSymbol=r;g.disableSchedulerTimeoutInWorkLoop=s;g.enableSchedulingProfiler=c}),98);
__d("TransAppInlineMode",[],(function(a,b,c,d,e,f){a=Object.freeze({STRING_MANAGER:"STRING_MANAGER",TRANSLATION:"TRANSLATION",APPROVE:"APPROVE",REPORT:"REPORT",NO_INLINE:"NO_INLINE"});f["default"]=a}),66);
__d("WAWebCleanAssets",["WAStorageEstimator","WAWebAssetLoaderDpiChangeDispatch","WAWebFeatureDetectionDetectWebpSupport","WAWebFeatureDetectionSwSupport","WAWebNoop","WAWebSWBus","WAWebSWBusActions","WAWebWebcStorageStatWamEvent","lodash"],(function(a,b,c,d,e,f,g){var h={DEFAULT:"default",WEBP:"webp"};function a(a){if(!c("WAWebFeatureDetectionSwSupport").supported)return;var b=a.estimateStorage===!0,e=navigator.serviceWorker;d("WAWebFeatureDetectionDetectWebpSupport").detectWebpSupport().then(function(b){var d=c("lodash").flatMap(a.keep,function(a){return[a[c("WAWebAssetLoaderDpiChangeDispatch").RES.LOW],a[c("WAWebAssetLoaderDpiChangeDispatch").RES.HIGH]]}).map(function(a){var c=b&&a[h.WEBP]?h.WEBP:h.DEFAULT;c=(a=a[c])==null?void 0:a.split("/");return c!=null?c[c.length-1]:null});e!=null&&e.controller&&c("WAWebSWBus").request(e.controller,c("WAWebSWBusActions").CLEAN_ASSETS,d)["catch"](c("WAWebNoop"))}).then(function(){return b?d("WAStorageEstimator").estimateStorage():null}).then(function(a){if(a!=null&&a.success){a=a.value;var b=a.usage;a=a.quota;new(d("WAWebWebcStorageStatWamEvent").WebcStorageStatWamEvent)({webcStorageUsage:b,webcStorageQuota:a}).commit()}})}g["default"]=a}),98);
__d("getUnwrappedFbt",["FbtResultGK"],(function(a,b,c,d,e,f){function a(a){a=a.contents;var c=b("FbtResultGK").inlineMode,d=b("FbtResultGK").shouldReturnFbtResult;if(!d&&c!=="REPORT")return(a==null?void 0:a.length)===1&&typeof a[0]==="string"?a[0]:a}e.exports=a}),null);
__d("getFbtResult",["FbtResult","FbtResultGK","InlineFbtResult","getUnwrappedFbt","gkx","recoverableViolation"],(function(a,b,c,d,e,f,g){c("gkx")("20935")&&c("FbtResultGK").inlineMode==="TRANSLATION"&&c("recoverableViolation")("TransAppInlineMode=TRANSLATION should not happen on Comet yet. "+("[inlineMode="+(c("FbtResultGK").inlineMode!=null?c("FbtResultGK").inlineMode:"")+"]")+("[runtime_site_is_comet="+String(c("gkx")("20935"))+"]"),"internationalization");function a(a){var b=c("getUnwrappedFbt")(a);if(b!=null)return b;b=a.contents;var d=a.patternString,e=a.patternHash;return c("FbtResultGK").inlineMode!=null&&c("FbtResultGK").inlineMode!=="NO_INLINE"?new(c("InlineFbtResult"))(b,c("FbtResultGK").inlineMode,d,e):c("FbtResult").get(a)}g["default"]=a}),98);
__d("hero-tracing-placeholder",["HeroComponent.react","HeroCurrentInteractionForLoggingContext","HeroHoldTrigger.react","HeroInteractionContext","HeroInteractionContextPassthrough.react","HeroInteractionIDContext","HeroPendingPlaceholderTracker","HeroPlaceholder.react","HeroPlaceholderUtils"],(function(a,b,c,d,e,f,g){"use strict";g.HeroComponent=c("HeroComponent.react"),g.HeroHoldTrigger=c("HeroHoldTrigger.react"),g.HeroInteractionContext=d("HeroInteractionContext"),g.HeroInteractionContextPassthrough=c("HeroInteractionContextPassthrough.react"),g.HeroInteractionIDContext=c("HeroInteractionIDContext"),g.HeroCurrentInteractionForLoggingContext=c("HeroCurrentInteractionForLoggingContext"),g.HeroPendingPlaceholderTracker=d("HeroPendingPlaceholderTracker"),g.HeroPlaceholder=c("HeroPlaceholder.react"),g.HeroPlaceholderUtils=d("HeroPlaceholderUtils")}),98);
__d("scheduler",["SchedulerFb-Internals_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";e.exports=b("SchedulerFb-Internals_DO_NOT_USE")}),null);
__d("setTimeoutCometLoggingPri",["cr:619"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:619")}),98);
__d("setTimeoutCometLoggingPriWWW",["JSScheduler","setTimeoutCometInternals"],(function(a,b,c,d,e,f,g){"use strict";var h;function a(a,b){for(var c=arguments.length,e=new Array(c>2?c-2:0),f=2;f<c;f++)e[f-2]=arguments[f];return d("setTimeoutCometInternals").setTimeoutAtPriority_DO_NOT_USE.apply(d("setTimeoutCometInternals"),[(h||(h=d("JSScheduler"))).priorities.unstable_Low,a,b].concat(e))}g["default"]=a}),98);/*FB_PKG_DELIM*/
__d("CometRouterRouteTracePolicyContext",["react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b=a.createContext();g["default"]=b}),98);
__d("CometTailLoadLogger",["QuickLogActionType","QuickPerformanceLogger","SiteData","VisibilityListener","gkx","performanceNavigationStart","qpl","uuidv4"],(function(a,b,c,d,e,f,g){"use strict";var h,i=3e3,j=c("gkx")("1326"),k=0,l=c("performanceNavigationStart")(),m=new Map(),n=new Map(),o=new Map(),p=new Set(),q=c("uuidv4")(),r=new Set();function a(){m.clear(),n.clear(),o.clear(),p.clear()}function s(a,b,d){k++;j&&(h||(h=c("QuickPerformanceLogger"))).markerStart(c("qpl")._(588713587,"4750"),k,d.current+l,{trackedForLoss:!0});d=a+"_"+b;o.set(d,k)}function b(a,b){n.set(a,b.current)}function e(a,b,c){a=a+"_"+b;m.set(a,c)}function t(a,b,e,f,g){var k=a+"_"+b,t=0,u=n.get(a)||e,v=m.get(k);v!=null&&(t=v,m["delete"](k));v=o.get(k);v==null&&(s(a,b,{current:u}),v=o.get(k));u=d("VisibilityListener").getHiddenTime(u+c("performanceNavigationStart")(),e+c("performanceNavigationStart")());j&&((h||(h=c("QuickPerformanceLogger"))).markerAnnotate(c("qpl")._(588713587,"4750"),{"int":{client_revision:c("SiteData").client_revision,hidden:Number(u!=null&&u>0),interruptedConsumption:t,position:b,windowHeight:Math.floor(window.innerHeight/100)},string:{client_push_phase:c("SiteData").push_phase,pageletName:a,sessionId:q,tracePolicy:g}},{instanceKey:v}),h.markerEnd(c("qpl")._(588713587,"4750"),f,v,e+l));if(f!==2||f===706&&t>=i){u=Object.keys(c("QuickLogActionType")).find(function(a){return c("QuickLogActionType")[a]===f})||"UNKNOWN";r.add({position:b,scrollingFNLType:u,tracePolicy:g})}p.add(k);o["delete"](k)}function f(a,b,c,d,e){var f=a+"_"+b,g=!p.has(f);g&&t(a,b,c,d,e);p["delete"](f)}function u(){return r}g.alreadyFinishedMarkerKeys=p;g.reset=a;g.startTailLoadTracing=s;g.setTailLoadStartTime=b;g.reportInterruptedConsumption=e;g.endTailloadTracing=t;g.logMarkerEnd=f;g.dump=u}),98);
__d("HeroTracingCoreConfigWWW",["gkx"],(function(a,b,c,d,e,f,g){"use strict";b={alwaysMarkMutationRootAsVisualChange:(a=c("gkx"))("20863"),enableCascadingRenderDetector:a("12285"),enableHeroLoggingVerbose:a("10725"),enableReactProfiling:a("12286"),enableResetCompletedFix:a("12288"),enableTrackName:!0,enablePlaceholderVCLogging:a("15960"),fixParentInteractionIdWhenCancel:a("12343"),observeMutationOnStart:!0,removeHoldOnParentContextOnNewInteraction:a("12290")};g["default"]=b}),98);
__d("useCometRouteTracePolicy",["CometRouterRouteTracePolicyContext","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i=(h||d("react")).useContext,j="comet.app";function a(){var a;return(a=i(c("CometRouterRouteTracePolicyContext")))!=null?a:j}g["default"]=a}),98);
__d("useCometTailLoadPageletTracker",["CometTailLoadLogger","intersectionObserverEntryIsIntersecting","react","useCometRouteTracePolicy"],(function(a,b,c,d,e,f,g){"use strict";var h;b=h||d("react");var i=b.useCallback,j=b.useRef;function a(a,b,e){var f=j(null),g=j(!1),h=j(null),k=c("useCometRouteTracePolicy")();return i(function(i){if(i==null){h.current==null||h.current();h.current=null;return}if(e===!0&&a!=null&&b!=null&&f.current!==i){f.current=i;var j=function(e){Array.prototype.forEach.call(e,function(e){c("intersectionObserverEntryIsIntersecting")(e)&&!g.current&&(g.current=!0,h.current==null||h.current(),h.current=null,d("CometTailLoadLogger").logMarkerEnd(a,b,e.time,2,k))})},l=new IntersectionObserver(j);l.observe(i);h.current=function(){f.current=null,l.disconnect()}}},[a,b,e])}g["default"]=a}),98);
__d("HeroTracingCoreDependenciesWWW",["cr:3798","useCometTailLoadPageletTracker"],(function(a,b,c,d,e,f,g){"use strict";a={useTailLoadPageletTracker:c("useCometTailLoadPageletTracker"),UserTimingUtils:b("cr:3798")};g["default"]=a}),98);
__d("ImageDownloadTrackerWWW",["NetworkStatus","Promise","setTimeout"],(function(a,b,c,d,e,f,g){"use strict";var h,i=2,j=250;function a(a,d){var e=0,f;return new(h||(h=b("Promise")))(function(b,g){function h(){var f=new Image();f.onload=function(){c("NetworkStatus").reportSuccess(),b()};f.onerror=function(){var a=e<=i;a?c("setTimeout")(h,j):(c("NetworkStatus").reportError(),g())};e++;d();f.src=a}c("NetworkStatus").isOnline()?h():f=c("NetworkStatus").onChange(function(a){a=a.online;a&&(h(),f.remove())})})}g["default"]=a}),98);
__d("InlineFbtResultImplComet",["FbtHooks","FbtReactUtil","FbtResultBase","react","recoverableViolation"],(function(a,b,c,d,e,f,g){"use strict";var h,i,j=i||d("react");function k(a){var b=a.content,d=a.hash,e=a.inlineMode;a=a.translation;d==null&&c("recoverableViolation")('Fbt string hash should not be null for translated string "'+a+'" '+("[inlineMode="+e+"]"),"internationalization");return j.jsx("span",{"data-intl-hash":d,"data-intl-translation":a,"data-intl-trid":"",children:b})}k.displayName=k.name+" [from "+f.id+"]";a=function(a){function b(b,e,f,g){var i;i=a.call(this,b,(h||(h=c("FbtHooks"))).getErrorListener({hash:g,translation:f}))||this;i.$$typeof=d("FbtReactUtil").REACT_ELEMENT_TYPE;i.key=null;i.ref=null;i.type=k;i.props={content:b,hash:g,inlineMode:e,translation:f};return i}babelHelpers.inheritsLoose(b,a);return b}(c("FbtResultBase"));g["default"]=a}),98);
__d("deferredLoadComponentBase",["ExecutionEnvironment","Promise","PromiseAnnotate","react","suspendOrThrowIfUsedInSSR"],(function(a,b,c,d,e,f,g){var h=["ref"],i=["loadImmediately"],j,k,l,m,n,o=n||c("react"),p={},q={},r=new Map();function s(a,b){r.set(a,b)}function t(a){return r.get(a)}function a(a,e){var g=t(a);if(g)return g;var n,r=a.getModuleId();function u(){var c=q[r];c||(c=q[r]=new(k||(k=b("Promise")))(function(b){a.loadImmediately(function(a){delete q[r],n=e(a),b()})}));return c}function v(){var c=p[r];c||(c=p[r]=new(k||(k=b("Promise")))(function(b){a.onReady(function(a){n=e(a),delete p[r],b()})}));return c}function w(b){var f=b.ref;b=babelHelpers.objectWithoutPropertiesLoose(b,h);var g=b.loadImmediately;b=babelHelpers.objectWithoutPropertiesLoose(b,i);if(!n){var k=a.getModuleIfRequireable();k!=null&&(n=e(k));if(!n){!(l||(l=c("ExecutionEnvironment"))).isInBrowser&&!a.isAvailableInSSR_DO_NOT_USE()&&(m||(m=c("suspendOrThrowIfUsedInSSR")))("Loading bootloaded and T3 components are disabled during SSR");k=g===!0?u():v();(j||(j=d("PromiseAnnotate"))).setDisplayName(k,w.displayName);throw k}}return o.jsx(n,babelHelpers["extends"]({},b,{ref:f}))}w.displayName=w.name+" [from "+f.id+"]";g=a.getModuleId();a.isRequireDeferredForDisplay()===!0?g="requireDeferredForDisplay"+("("+a.getModuleId()+")"):a.isRequireDeferredForDisplay()===!1&&(g="requireDeferred"+("("+a.getModuleId()+")"));w.displayName="deferredLoadComponent("+g+")";g=w;s(a,g);return g}g["default"]=a}),98);
__d("deferredLoadComponent",["deferredLoadComponentBase"],(function(a,b,c,d,e,f,g){var h=function(a){return a};function a(a){return c("deferredLoadComponentBase")(a,h)}g["default"]=a}),98);/*FB_PKG_DELIM*/
/**
 * License: https://www.facebook.com/legal/license/V9vdYColc4k/
 */
__d("react-0.0.0",["React"],(function(a,b,c,d,e,f){"use strict";function a(a){return a&&typeof a==="object"&&"default"in a?a["default"]:a}var g=a(b("React"));d={};var h={exports:d};function i(){h.exports=g}var j=!1;function k(){j||(j=!0,i());return h.exports}function c(a){switch(a){case void 0:return k()}}e.exports=c}),null);
__d("react",["react-0.0.0"],(function(a,b,c,d,e,f){e.exports=b("react-0.0.0")()}),null);